apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": "tikv", "partner_name": "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Longhorn
    version: "{{ .Values.longhorn.engine.image.tag }}"
    description: |-
      Longhorn is a lightweight, reliable and easy-to-use distributed block storage system for Kubernetes. 
      # Support
      Google does not offer support for this solution. However, community support is available on
      [Stack Overflow](https://stackoverflow.com/questions/tagged/longhorn/).
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy Longhorn'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/longhorn/README.md
    - description: 'Official documentation for Longhorn'
      url: https://longhorn.io/docs/1.3.2/what-is-longhorn/
    notes: |-
      Bicho de sete cabeças
  info:
  - name: Longhorn
    type: Reference
    valueFrom:
      serviceRef:
        name: {{ .Release.Name }}-Longhorn
  - name: Application Namespace
    value: {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: apps/v1
    kind: Deployment
  - group: apps/v1
    kind: DaemonSet
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Service
  {{ if .Values.enablePublicServiceAndIngress }}
  - group: networking.k8s.io
    kind: Ingress
  {{ end }}
  - group: v1
    kind: ServiceAccount
  - group: rbac.authorization.k8s.io/v1
    kind:  ClusterRole
  - group: rbac.authorization.k8s.io/v1
    kind:  ClusterRoleBinding

