x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
      - Feature
    recommended: false

  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 6
        memory: 8Gi

  images:
    '':
      properties:
        longhorn.engine.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.engine.image.tag:
          type: TAG

    longhorn-manager:
      properties:
        longhorn.manager.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.manager.image.tag:
          type: TAG

    longhorn-ui:
      properties:
        longhorn.ui.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.ui.image.tag:
          type: TAG

    longhorn-instance-manager:
      properties:
        longhorn.instance-manager.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.instance-manager.istiod.image.tag:
          type: TAG

    longhorn-share-manager:
      properties:
        longhorn.share-manager.image.repo:
          type: REPO_WITH_REGISTRY
        knative.serving.activator.image.tag:
          type: TAG

    longhorn-backing-image-manager:
      properties:
        longhorn.backing-image-manager.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.backing-image-manager.image.tag:
          type: TAG

    longhorn-csi-attacher:
      properties:
        longhorn.csi-attacher.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.csi-attacher.image.tag:
          type: TAG

    longhorn-csi-provisioner:
      properties:
        longhorn.csi-provisioner.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.csi-provisioner.image.tag:
          type: TAG

    longhorn-csi-node-driver-registrar:
      properties:
        longhorn.csi-node-driver-registrar.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.csi-node-driver-registrar.image.tag:
          type: TAG

    longhorn-csi-resizer:
      properties:
        longhorn.csi-resizer.image.repo:
          type: REPO_WITH_REGISTRY
        longhorn.csi-resizer.image.tag:
          type: TAG

    longhorn-csi-snapshotter:
      properties:
        longhorn.csi-snapshotter.image.repo:
          type: REPO_WITH_REGI:57,105STRY
        longhorn.csi-snapshotter.image.tag:
          type: TAG

  deployerServiceAccount:
    description: Creates app resources, including Webhooks and ClusterRoleBindings.
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups:
            - 'rbac.authorization.k8s.io'
            resources:
            - 'clusterroles'
            - 'clusterrolebindings'
            verbs:
            - '*'
          - apiGroups: 
            - 'apiextensions.k8s.io'
            resources: 
            - 'customresourcedefinitions'
            verbs: 
            - '*'
          - apiGroups:
            - 'admissionregistration.k8s.io'
            resources:
            - 'mutatingwebhookconfigurations'
            - 'validatingwebhookconfigurations'
            verbs:
            - '*'
          - apiGroups:
            - ''
            resources:
            - 'namespaces'
            verbs:
            - 'create'
            - 'list'
            - 'update'
            - 'patch'

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  certmanager.controller.replicas:
    type: integer
    title: Certmanager controller replicas
    description: Number of replicas of the Cert Manager controller
    default: 1
    enum:
      - '1'
      - '3'
      - '5'
  certmanager.webhook.replicas:
    type: integer
    title: Certmanager webhook replicas
    description: Number of replicas of the Cert Manager webhook
    default: 1
    enum:
      - '1'
      - '3'
      - '5'
  certmanager.cainjector.replicas:
    type: integer
    title: Certmanager CA injector replicas
    description: Number of replicas of the Cert Manager CA Injector
    default: 1
    enum:
      - '1'
      - '3'
      - '5'
  istio.ingressgateway.replicas:
    type: integer
    title: Istio Ingress Gateway replicas
    description: Number of replicas of the Istio Ingress Gateway
    default: 1
    enum:
      - '1'
      - '3'
      - '5'
  knative.serving.autoscaler.replicas:
    type: integer
    title: Knative serving autoscaler replicas
    description: Number of replicas of the Knative serving autoscaler
    default: 1
    enum:
      - '1'
      - '3'
      - '5'
  knative.eventing.mtping.replicas:
    type: integer
    title: Knative eventing mtping replicas
    description: Number of replicas of the Knative eventing mtping
    default: 1
    minimum: 0
required:
- name
- namespace
- certmanager.controller.replicas
- certmanager.webhook.replicas
- certmanager.cainjector.replicas
- istio.ingressgateway.replicas
- knative.serving.autoscaler.replicas
- knative.eventing.mtping.replicas
