---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-superset-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: apache-superset
type: Opaque
data:
  superset-password: {{ .Values.superset.password | b64enc | quote }}
{{ if .Values.enablePublicServiceAndIngress }}
{{ end }}