---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-superset-svc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: apache-superset
spec:
  ports:
  - name: http
    port: 8088
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: apache-superset
  {{ if .Values.enablePublicServiceAndIngress }}
  type: LoadBalancer
  {{ else }}
  type: ClusterIP
  {{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-superset-ingress
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: apache-superset
spec:
  tls:
  - secretName: {{ .Release.Name }}-tls
  defaultBackend:
    service:
      name: {{ .Release.Name }}-superset-svc
      port:
        name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-statsd-exporter-svc
  annotations:
    prometheus.io/port: "9102"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: superset-statsd
spec:
  ports:
    - port: 9102
      targetPort: 9102
      protocol: TCP
      name: exporter
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: superset-statsd
  type: ClusterIP
