---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tikv
  labels: &tikvLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: tikv-server
spec:
  ports:
  - name: client
    port: 20160
    protocol: TCP
  - name: status
    port: 20180
    protocol: TCP
  selector: *tikvLabels
  type: ClusterIP

